/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package miniprojet;

import java.sql.*;

/*
Bibliotheque extern
*/
import mdlaf.*;
import mdlaf.animation.*;
import javax.swing.*;
import java.awt.*;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import mdlaf.utils.MaterialColors;

/**
 *
 * @author najibboubrim
 */
public class login extends javax.swing.JFrame {
    
        Connection con = null;
        //PreparedStatement pst = null;
        Statement st = null;
        ResultSet rs = null;
        


    /**
     * Creates new form login
     */
    public login() {
        initComponents();
        afficherSalles();
    }
    
    public ArrayList<Salle> listeSalles() {
    ArrayList<Salle> listeSalles = new ArrayList<>();
    
    try{
    con = MySqlConnect.ConnectDB();
    String query2 = "select * from Salle";
    Statement st2 = con.createStatement();
    ResultSet rs2 = st2.executeQuery(query2);

    Salle salle;
    
    while(rs2.next()) {
        salle = new Salle(rs2.getInt("numSalle"), rs2.getInt("reservationMatin"), rs2.getInt("reservationApresMidi"), rs2.getInt("reservationSoiree"));
        listeSalles.add(salle);
    }
    
    } catch(Exception ex) {
        JOptionPane.showMessageDialog(null, ex);
    }
    
    return listeSalles;
}
    
    public void afficherSalles() {
        ArrayList<Salle> list = listeSalles();
        DefaultTableModel model = (DefaultTableModel)consult_table.getModel();
        Object[] row = new Object[6];
        for(int i=0; i<list.size(); i++) {
            row[0] = list.get(i).getNumSalle();
            row[1] = list.get(i).getReservationMatin();
            row[2] = list.get(i).getReservationApresMidi();
            row[3] = list.get(i).getReservationSoiree();
            model.addRow(row);
        }
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jFrame1 = new javax.swing.JFrame();
        jPanel2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jFrame2 = new javax.swing.JFrame();
        jPanel3 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jFrame3 = new javax.swing.JFrame();
        jPanel4 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jFrame4 = new javax.swing.JFrame();
        jPanel5 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jFrame5 = new javax.swing.JFrame();
        jPanel6 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jPasswordField2 = new javax.swing.JPasswordField();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jFrame6 = new javax.swing.JFrame();
        jPanel7 = new javax.swing.JPanel();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jLabel25 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel29 = new javax.swing.JLabel();
        jFrame7 = new javax.swing.JFrame();
        jPanel11 = new javax.swing.JPanel();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jLabel32 = new javax.swing.JLabel();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel30 = new javax.swing.JLabel();
        jDialog1 = new javax.swing.JDialog();
        jPanel8 = new javax.swing.JPanel();
        jLabel31 = new javax.swing.JLabel();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jLabel36 = new javax.swing.JLabel();
        jDialog2 = new javax.swing.JDialog();
        jPanel9 = new javax.swing.JPanel();
        jLabel33 = new javax.swing.JLabel();
        jButton13 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jLabel37 = new javax.swing.JLabel();
        consultFrame = new javax.swing.JFrame();
        jPanel10 = new javax.swing.JPanel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        consult_table = new javax.swing.JTable();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        imprimerFrame = new javax.swing.JFrame();
        jPanel15 = new javax.swing.JPanel();
        jLabel55 = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        jLabel57 = new javax.swing.JLabel();
        jLabel58 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jLabel59 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jLabel60 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox();
        jButton19 = new javax.swing.JButton();
        reserverSalle = new javax.swing.JFrame();
        jPanel12 = new javax.swing.JPanel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel47 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel48 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jButton17 = new javax.swing.JButton();
        annulerReservation = new javax.swing.JFrame();
        jPanel14 = new javax.swing.JPanel();
        jLabel49 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel53 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabel54 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox();
        jButton18 = new javax.swing.JButton();
        jDialog3 = new javax.swing.JDialog();
        jPanel13 = new javax.swing.JPanel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jDialog4 = new javax.swing.JDialog();
        jPanel16 = new javax.swing.JPanel();
        jLabel61 = new javax.swing.JLabel();
        jLabel62 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        facture_table = new javax.swing.JTable();
        enregistrerVFrame = new javax.swing.JFrame();
        jPanel18 = new javax.swing.JPanel();
        jLabel69 = new javax.swing.JLabel();
        jLabel70 = new javax.swing.JLabel();
        jLabel71 = new javax.swing.JLabel();
        jLabel72 = new javax.swing.JLabel();
        jTextField11 = new javax.swing.JTextField();
        jButton21 = new javax.swing.JButton();
        verserFrame = new javax.swing.JFrame();
        jPanel17 = new javax.swing.JPanel();
        jLabel63 = new javax.swing.JLabel();
        jLabel64 = new javax.swing.JLabel();
        jLabel65 = new javax.swing.JLabel();
        jLabel66 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jLabel67 = new javax.swing.JLabel();
        jButton20 = new javax.swing.JButton();
        jComboBox4 = new javax.swing.JComboBox();
        jPanel1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();

        jFrame1.setBounds(new java.awt.Rectangle(600, 400, 370, 120));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(null);

        jLabel9.setFont(new java.awt.Font("Lato", 1, 18)); // NOI18N
        jLabel9.setText("Wilaya de Mila - Mlia Centre");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(90, 50, 230, 22);

        jLabel10.setIcon(new javax.swing.ImageIcon("/Users/najibboubrim/Desktop/JB/icons8-address-96.png")); // NOI18N
        jPanel2.add(jLabel10);
        jLabel10.setBounds(190, 10, 30, 40);

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 386, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jFrame2.setBounds(new java.awt.Rectangle(600, 400, 370, 120));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(null);

        jLabel11.setFont(new java.awt.Font("Lato", 1, 18)); // NOI18N
        jLabel11.setText("031 66 66 66 - 031 55 55 55");
        jPanel3.add(jLabel11);
        jLabel11.setBounds(90, 50, 230, 22);

        jLabel12.setIcon(new javax.swing.ImageIcon("/Users/najibboubrim/Desktop/JB/icons8-ringer-volume-96.png")); // NOI18N
        jPanel3.add(jLabel12);
        jLabel12.setBounds(190, 10, 30, 40);

        javax.swing.GroupLayout jFrame2Layout = new javax.swing.GroupLayout(jFrame2.getContentPane());
        jFrame2.getContentPane().setLayout(jFrame2Layout);
        jFrame2Layout.setHorizontalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 386, Short.MAX_VALUE)
        );
        jFrame2Layout.setVerticalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jFrame3.setBounds(new java.awt.Rectangle(600, 400, 370, 120));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(null);

        jLabel13.setFont(new java.awt.Font("Lato", 1, 18)); // NOI18N
        jLabel13.setText("wilaya_de_mila@wilaya.dz");
        jPanel4.add(jLabel13);
        jLabel13.setBounds(100, 50, 230, 22);

        jLabel14.setIcon(new javax.swing.ImageIcon("/Users/najibboubrim/Desktop/JB/icons8-email-sign-96.png")); // NOI18N
        jPanel4.add(jLabel14);
        jLabel14.setBounds(190, 10, 30, 40);

        javax.swing.GroupLayout jFrame3Layout = new javax.swing.GroupLayout(jFrame3.getContentPane());
        jFrame3.getContentPane().setLayout(jFrame3Layout);
        jFrame3Layout.setHorizontalGroup(
            jFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 386, Short.MAX_VALUE)
        );
        jFrame3Layout.setVerticalGroup(
            jFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jFrame4.setBounds(new java.awt.Rectangle(450, 200, 690, 533));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel5MouseClicked(evt);
            }
        });
        jPanel5.setLayout(null);

        jLabel17.setFont(new java.awt.Font("Seravek", 1, 48)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Gestionnaire Municipal");
        jPanel5.add(jLabel17);
        jLabel17.setBounds(100, 50, 530, 70);

        jLabel18.setIcon(new javax.swing.ImageIcon("/Users/najibboubrim/Desktop/JB/BG.jpg")); // NOI18N
        jPanel5.add(jLabel18);
        jLabel18.setBounds(0, 0, 690, 170);

        jLabel19.setIcon(new javax.swing.ImageIcon("/Users/najibboubrim/Desktop/JB/icons8-gears-96.png")); // NOI18N
        jPanel5.add(jLabel19);
        jLabel19.setBounds(350, 180, 90, 90);

        jLabel20.setIcon(new javax.swing.ImageIcon("/Users/najibboubrim/Desktop/JB/icons8-male-user-96.png")); // NOI18N
        jPanel5.add(jLabel20);
        jLabel20.setBounds(280, 200, 120, 90);

        jLabel21.setFont(new java.awt.Font("Lato", 0, 13)); // NOI18N
        jLabel21.setText("nom d'utilisateur");
        jPanel5.add(jLabel21);
        jLabel21.setBounds(250, 320, 100, 16);

        jLabel22.setFont(new java.awt.Font("Lato", 0, 13)); // NOI18N
        jLabel22.setText("mot de passe");
        jPanel5.add(jLabel22);
        jLabel22.setBounds(250, 370, 80, 16);

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel5.add(jTextField1);
        jTextField1.setBounds(250, 340, 200, 26);

        jPasswordField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField1ActionPerformed(evt);
            }
        });
        jPanel5.add(jPasswordField1);
        jPasswordField1.setBounds(250, 390, 200, 26);

        jButton2.setFont(new java.awt.Font("Lato", 1, 13)); // NOI18N
        jButton2.setText("S'authentifier");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton2);
        jButton2.setBounds(250, 420, 200, 29);

        jButton3.setFont(new java.awt.Font("Lato", 1, 13)); // NOI18N
        jButton3.setText("Retour");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton3);
        jButton3.setBounds(250, 450, 200, 29);

        javax.swing.GroupLayout jFrame4Layout = new javax.swing.GroupLayout(jFrame4.getContentPane());
        jFrame4.getContentPane().setLayout(jFrame4Layout);
        jFrame4Layout.setHorizontalGroup(
            jFrame4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, 690, Short.MAX_VALUE)
        );
        jFrame4Layout.setVerticalGroup(
            jFrame4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrame4Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 533, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jFrame5.setBounds(new java.awt.Rectangle(450, 200, 690, 533));

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel6MouseClicked(evt);
            }
        });
        jPanel6.setLayout(null);

        jLabel23.setFont(new java.awt.Font("Seravek", 1, 48)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("Usager");
        jPanel6.add(jLabel23);
        jLabel23.setBounds(280, 50, 160, 70);

        jLabel24.setIcon(new javax.swing.ImageIcon("/Users/najibboubrim/Desktop/JB/BG.jpg")); // NOI18N
        jPanel6.add(jLabel24);
        jLabel24.setBounds(0, 0, 690, 170);

        jLabel26.setIcon(new javax.swing.ImageIcon("/Users/najibboubrim/Desktop/JB/icons8-male-user-96.png")); // NOI18N
        jPanel6.add(jLabel26);
        jLabel26.setBounds(310, 200, 96, 90);

        jLabel27.setFont(new java.awt.Font("Lato", 0, 13)); // NOI18N
        jLabel27.setText("nom d'utilisateur");
        jPanel6.add(jLabel27);
        jLabel27.setBounds(250, 320, 120, 16);

        jLabel28.setFont(new java.awt.Font("Lato", 0, 13)); // NOI18N
        jLabel28.setText("mot de passe");
        jPanel6.add(jLabel28);
        jLabel28.setBounds(250, 370, 80, 16);

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        jPanel6.add(jTextField2);
        jTextField2.setBounds(250, 340, 200, 26);

        jPasswordField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField2ActionPerformed(evt);
            }
        });
        jPanel6.add(jPasswordField2);
        jPasswordField2.setBounds(250, 390, 200, 26);

        jButton4.setFont(new java.awt.Font("Lato", 1, 13)); // NOI18N
        jButton4.setText("S'authentifier");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton4);
        jButton4.setBounds(250, 420, 200, 29);

        jButton5.setFont(new java.awt.Font("Lato", 1, 13)); // NOI18N
        jButton5.setText("Retour");
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton5MouseClicked(evt);
            }
        });
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton5);
        jButton5.setBounds(250, 450, 200, 29);

        javax.swing.GroupLayout jFrame5Layout = new javax.swing.GroupLayout(jFrame5.getContentPane());
        jFrame5.getContentPane().setLayout(jFrame5Layout);
        jFrame5Layout.setHorizontalGroup(
            jFrame5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, 690, Short.MAX_VALUE)
        );
        jFrame5Layout.setVerticalGroup(
            jFrame5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrame5Layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 533, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jFrame6.setBounds(new java.awt.Rectangle(450, 200, 669, 496));

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel7MouseClicked(evt);
            }
        });
        jPanel7.setLayout(null);

        jButton6.setFont(new java.awt.Font("Lato", 1, 18)); // NOI18N
        jButton6.setText("Imprimer Facture");
        jButton6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton6MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton6MouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton6MouseEntered(evt);
            }
        });
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton6);
        jButton6.setBounds(180, 280, 320, 60);

        jButton7.setFont(new java.awt.Font("Lato", 1, 18)); // NOI18N
        jButton7.setText("Consulter Planing d'occupation");
        jButton7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton7MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton7MouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton7MouseEntered(evt);
            }
        });
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton7);
        jButton7.setBounds(180, 140, 320, 60);

        jButton8.setFont(new java.awt.Font("Lato", 1, 18)); // NOI18N
        jButton8.setText("Enregistrer Versement");
        jButton8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton8MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton8MouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton8MouseEntered(evt);
            }
        });
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton8);
        jButton8.setBounds(180, 210, 320, 60);

        jLabel25.setFont(new java.awt.Font("Lato", 1, 18)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("Decconecter");
        jLabel25.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel25MouseClicked(evt);
            }
        });
        jPanel7.add(jLabel25);
        jLabel25.setBounds(290, 360, 110, 30);
        jPanel7.add(jSeparator3);
        jSeparator3.setBounds(310, 390, 70, 20);

        jLabel29.setIcon(new javax.swing.ImageIcon("/Users/najibboubrim/Desktop/JB/BG.jpg")); // NOI18N
        jPanel7.add(jLabel29);
        jLabel29.setBounds(0, -10, 690, 520);

        javax.swing.GroupLayout jFrame6Layout = new javax.swing.GroupLayout(jFrame6.getContentPane());
        jFrame6.getContentPane().setLayout(jFrame6Layout);
        jFrame6Layout.setHorizontalGroup(
            jFrame6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, 669, Short.MAX_VALUE)
        );
        jFrame6Layout.setVerticalGroup(
            jFrame6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 496, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jFrame7.setBounds(new java.awt.Rectangle(450, 200, 669, 496));
        jFrame7.setPreferredSize(new java.awt.Dimension(669, 496));

        jPanel11.setLayout(null);

        jButton11.setFont(new java.awt.Font("Lato", 1, 18)); // NOI18N
        jButton11.setText("Consulter Planing d'occupation");
        jButton11.setPreferredSize(new java.awt.Dimension(320, 60));
        jButton11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton11MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton11MouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton11MouseEntered(evt);
            }
        });
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        jPanel11.add(jButton11);
        jButton11.setBounds(170, 50, 307, 72);

        jButton12.setFont(new java.awt.Font("Lato", 1, 18)); // NOI18N
        jButton12.setText("Réserver une salle");
        jButton12.setPreferredSize(new java.awt.Dimension(307, 72));
        jButton12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton12MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton12MouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton12MouseEntered(evt);
            }
        });
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        jPanel11.add(jButton12);
        jButton12.setBounds(170, 130, 310, 72);

        jLabel32.setFont(new java.awt.Font("Lato", 1, 18)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(255, 255, 255));
        jLabel32.setText("Decconecter");
        jLabel32.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel32MouseClicked(evt);
            }
        });
        jPanel11.add(jLabel32);
        jLabel32.setBounds(270, 380, 104, 20);

        jButton14.setFont(new java.awt.Font("Lato", 1, 18)); // NOI18N
        jButton14.setText("Annuler une réservation");
        jButton14.setPreferredSize(new java.awt.Dimension(307, 72));
        jButton14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton14MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton14MouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton14MouseEntered(evt);
            }
        });
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });
        jPanel11.add(jButton14);
        jButton14.setBounds(170, 210, 310, 72);

        jButton15.setFont(new java.awt.Font("Lato", 1, 18)); // NOI18N
        jButton15.setText("Verser les frais");
        jButton15.setPreferredSize(new java.awt.Dimension(307, 72));
        jButton15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton15MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton15MouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton15MouseEntered(evt);
            }
        });
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });
        jPanel11.add(jButton15);
        jButton15.setBounds(170, 290, 307, 72);
        jPanel11.add(jSeparator2);
        jSeparator2.setBounds(290, 400, 70, 40);

        jLabel30.setIcon(new javax.swing.ImageIcon("/Users/najibboubrim/Desktop/JB/BG.jpg")); // NOI18N
        jPanel11.add(jLabel30);
        jLabel30.setBounds(0, 0, 800, 500);

        javax.swing.GroupLayout jFrame7Layout = new javax.swing.GroupLayout(jFrame7.getContentPane());
        jFrame7.getContentPane().setLayout(jFrame7Layout);
        jFrame7Layout.setHorizontalGroup(
            jFrame7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, 669, Short.MAX_VALUE)
        );
        jFrame7Layout.setVerticalGroup(
            jFrame7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrame7Layout.createSequentialGroup()
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, 511, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jDialog1.setBounds(new java.awt.Rectangle(600, 400, 496, 142));

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setLayout(null);

        jLabel31.setFont(new java.awt.Font("Lato", 1, 14)); // NOI18N
        jLabel31.setText("Voulez-vous vraiment deconnecter ?");
        jPanel8.add(jLabel31);
        jLabel31.setBounds(140, 40, 227, 17);

        jButton9.setText("Oui");
        jButton9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton9MouseClicked(evt);
            }
        });
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel8.add(jButton9);
        jButton9.setBounds(130, 80, 120, 29);

        jButton10.setText("Non");
        jButton10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton10MouseClicked(evt);
            }
        });
        jPanel8.add(jButton10);
        jButton10.setBounds(260, 80, 120, 29);

        jLabel36.setIcon(new javax.swing.ImageIcon("/Users/najibboubrim/Desktop/JB/icons8-high-priority-96.png")); // NOI18N
        jPanel8.add(jLabel36);
        jLabel36.setBounds(40, 10, 90, 80);

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, 496, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
        );

        jDialog2.setBounds(new java.awt.Rectangle(600, 400, 496, 142));

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));
        jPanel9.setLayout(null);

        jLabel33.setFont(new java.awt.Font("Lato", 1, 14)); // NOI18N
        jLabel33.setText("Voulez-vous vraiment deconnecter ?");
        jPanel9.add(jLabel33);
        jLabel33.setBounds(140, 40, 227, 17);

        jButton13.setText("Oui");
        jButton13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton13MouseClicked(evt);
            }
        });
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        jPanel9.add(jButton13);
        jButton13.setBounds(130, 80, 120, 29);

        jButton16.setText("Non");
        jButton16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton16MouseClicked(evt);
            }
        });
        jPanel9.add(jButton16);
        jButton16.setBounds(260, 80, 120, 29);

        jLabel37.setIcon(new javax.swing.ImageIcon("/Users/najibboubrim/Desktop/JB/icons8-high-priority-96.png")); // NOI18N
        jPanel9.add(jLabel37);
        jLabel37.setBounds(40, 10, 90, 80);

        javax.swing.GroupLayout jDialog2Layout = new javax.swing.GroupLayout(jDialog2.getContentPane());
        jDialog2.getContentPane().setLayout(jDialog2Layout);
        jDialog2Layout.setHorizontalGroup(
            jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, 496, Short.MAX_VALUE)
        );
        jDialog2Layout.setVerticalGroup(
            jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
        );

        consultFrame.setBounds(new java.awt.Rectangle(450, 200, 685, 594));

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));
        jPanel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel10MouseClicked(evt);
            }
        });
        jPanel10.setLayout(null);

        jLabel34.setFont(new java.awt.Font("Seravek", 1, 24)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(255, 255, 255));
        jLabel34.setText("Planing d'occupation des salles");
        jPanel10.add(jLabel34);
        jLabel34.setBounds(180, -10, 340, 70);

        jLabel35.setIcon(new javax.swing.ImageIcon("/Users/najibboubrim/Desktop/JB/BG.jpg")); // NOI18N
        jPanel10.add(jLabel35);
        jLabel35.setBounds(0, 0, 690, 60);

        consult_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Numero de salle", "Matin", "Aprés Midi", "Soirée"
            }
        ));
        jScrollPane1.setViewportView(consult_table);

        jPanel10.add(jScrollPane1);
        jScrollPane1.setBounds(20, 100, 650, 440);

        jLabel40.setFont(new java.awt.Font("Lato", 1, 13)); // NOI18N
        jLabel40.setText("Reservation : [0] = Non occupé [1] Occupé");
        jPanel10.add(jLabel40);
        jLabel40.setBounds(20, 540, 290, 40);

        jLabel41.setFont(new java.awt.Font("Lato", 1, 13)); // NOI18N
        jLabel41.setText("Frais");
        jLabel41.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel41MouseClicked(evt);
            }
        });
        jPanel10.add(jLabel41);
        jLabel41.setBounds(620, 550, 30, 20);

        jLabel42.setIcon(new javax.swing.ImageIcon("/Users/najibboubrim/Desktop/JB/icons8-paper-money-24.png")); // NOI18N
        jPanel10.add(jLabel42);
        jLabel42.setBounds(650, 550, 24, 20);

        javax.swing.GroupLayout consultFrameLayout = new javax.swing.GroupLayout(consultFrame.getContentPane());
        consultFrame.getContentPane().setLayout(consultFrameLayout);
        consultFrameLayout.setHorizontalGroup(
            consultFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, 684, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        consultFrameLayout.setVerticalGroup(
            consultFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, 594, Short.MAX_VALUE)
        );

        imprimerFrame.setBounds(new java.awt.Rectangle(0, 22, 781, 533));

        jPanel15.setBackground(new java.awt.Color(255, 255, 255));
        jPanel15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel15MouseClicked(evt);
            }
        });
        jPanel15.setLayout(null);

        jLabel55.setFont(new java.awt.Font("Seravek", 1, 24)); // NOI18N
        jLabel55.setForeground(new java.awt.Color(255, 255, 255));
        jLabel55.setText("Imprimer Facture");
        jPanel15.add(jLabel55);
        jLabel55.setBounds(310, 20, 200, 30);

        jLabel56.setIcon(new javax.swing.ImageIcon("/Users/najibboubrim/Desktop/JB/BG.jpg")); // NOI18N
        jPanel15.add(jLabel56);
        jLabel56.setBounds(0, 0, 800, 60);

        jLabel57.setFont(new java.awt.Font("Lato", 1, 16)); // NOI18N
        jLabel57.setText("Veuillez remplir les informations suivants :");
        jPanel15.add(jLabel57);
        jLabel57.setBounds(240, 150, 320, 20);

        jLabel58.setFont(new java.awt.Font("Lato", 1, 13)); // NOI18N
        jLabel58.setText("Numero d'usager");
        jPanel15.add(jLabel58);
        jLabel58.setBounds(240, 200, 120, 16);
        jPanel15.add(jTextField7);
        jTextField7.setBounds(240, 220, 250, 26);

        jLabel59.setFont(new java.awt.Font("Lato", 1, 13)); // NOI18N
        jLabel59.setText("Numero de salle reserver");
        jPanel15.add(jLabel59);
        jLabel59.setBounds(240, 260, 150, 16);
        jPanel15.add(jTextField8);
        jTextField8.setBounds(240, 280, 250, 26);

        jLabel60.setFont(new java.awt.Font("Lato", 1, 13)); // NOI18N
        jLabel60.setText("Horraire");
        jPanel15.add(jLabel60);
        jLabel60.setBounds(240, 320, 50, 16);

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Matin", "Aprés Midi", "Soirée" }));
        jPanel15.add(jComboBox3);
        jComboBox3.setBounds(240, 340, 270, 27);

        jButton19.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jButton19.setText("Imprimer");
        jButton19.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton19MouseClicked(evt);
            }
        });
        jButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton19ActionPerformed(evt);
            }
        });
        jPanel15.add(jButton19);
        jButton19.setBounds(265, 400, 200, 70);

        javax.swing.GroupLayout imprimerFrameLayout = new javax.swing.GroupLayout(imprimerFrame.getContentPane());
        imprimerFrame.getContentPane().setLayout(imprimerFrameLayout);
        imprimerFrameLayout.setHorizontalGroup(
            imprimerFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel15, javax.swing.GroupLayout.DEFAULT_SIZE, 781, Short.MAX_VALUE)
        );
        imprimerFrameLayout.setVerticalGroup(
            imprimerFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(imprimerFrameLayout.createSequentialGroup()
                .addComponent(jPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, 533, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        reserverSalle.setBounds(new java.awt.Rectangle(0, 22, 781, 533));

        jPanel12.setBackground(new java.awt.Color(255, 255, 255));
        jPanel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel12MouseClicked(evt);
            }
        });
        jPanel12.setLayout(null);

        jLabel38.setFont(new java.awt.Font("Seravek", 1, 24)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(255, 255, 255));
        jLabel38.setText("Reservation une salle");
        jPanel12.add(jLabel38);
        jLabel38.setBounds(270, 20, 230, 30);

        jLabel39.setIcon(new javax.swing.ImageIcon("/Users/najibboubrim/Desktop/JB/BG.jpg")); // NOI18N
        jPanel12.add(jLabel39);
        jLabel39.setBounds(0, 0, 800, 60);

        jLabel45.setFont(new java.awt.Font("Lato", 1, 16)); // NOI18N
        jLabel45.setText("Veuillez remplir les informations suivants :");
        jPanel12.add(jLabel45);
        jLabel45.setBounds(240, 150, 320, 20);

        jLabel46.setFont(new java.awt.Font("Lato", 1, 13)); // NOI18N
        jLabel46.setText("Numero d'usager");
        jPanel12.add(jLabel46);
        jLabel46.setBounds(240, 200, 120, 16);
        jPanel12.add(jTextField3);
        jTextField3.setBounds(240, 220, 250, 26);

        jLabel47.setFont(new java.awt.Font("Lato", 1, 13)); // NOI18N
        jLabel47.setText("Numero de salle");
        jPanel12.add(jLabel47);
        jLabel47.setBounds(240, 260, 110, 16);
        jPanel12.add(jTextField4);
        jTextField4.setBounds(240, 280, 250, 26);

        jLabel48.setFont(new java.awt.Font("Lato", 1, 13)); // NOI18N
        jLabel48.setText("Horraire");
        jPanel12.add(jLabel48);
        jLabel48.setBounds(240, 320, 50, 16);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Matin", "Aprés Midi", "Soirée" }));
        jPanel12.add(jComboBox1);
        jComboBox1.setBounds(240, 340, 270, 27);

        jButton17.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jButton17.setText("Rêserver");
        jButton17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton17MouseClicked(evt);
            }
        });
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });
        jPanel12.add(jButton17);
        jButton17.setBounds(295, 400, 140, 70);

        javax.swing.GroupLayout reserverSalleLayout = new javax.swing.GroupLayout(reserverSalle.getContentPane());
        reserverSalle.getContentPane().setLayout(reserverSalleLayout);
        reserverSalleLayout.setHorizontalGroup(
            reserverSalleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, 781, Short.MAX_VALUE)
        );
        reserverSalleLayout.setVerticalGroup(
            reserverSalleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(reserverSalleLayout.createSequentialGroup()
                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, 533, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        annulerReservation.setBounds(new java.awt.Rectangle(0, 22, 781, 533));

        jPanel14.setBackground(new java.awt.Color(255, 255, 255));
        jPanel14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel14MouseClicked(evt);
            }
        });
        jPanel14.setLayout(null);

        jLabel49.setFont(new java.awt.Font("Seravek", 1, 24)); // NOI18N
        jLabel49.setForeground(new java.awt.Color(255, 255, 255));
        jLabel49.setText("Annuler une reservation");
        jPanel14.add(jLabel49);
        jLabel49.setBounds(270, 20, 280, 30);

        jLabel50.setIcon(new javax.swing.ImageIcon("/Users/najibboubrim/Desktop/JB/BG.jpg")); // NOI18N
        jPanel14.add(jLabel50);
        jLabel50.setBounds(0, 0, 800, 60);

        jLabel51.setFont(new java.awt.Font("Lato", 1, 16)); // NOI18N
        jLabel51.setText("Veuillez remplir les informations suivants :");
        jPanel14.add(jLabel51);
        jLabel51.setBounds(240, 150, 320, 20);

        jLabel52.setFont(new java.awt.Font("Lato", 1, 13)); // NOI18N
        jLabel52.setText("Numero d'usager");
        jPanel14.add(jLabel52);
        jLabel52.setBounds(240, 200, 120, 16);
        jPanel14.add(jTextField5);
        jTextField5.setBounds(240, 220, 250, 26);

        jLabel53.setFont(new java.awt.Font("Lato", 1, 13)); // NOI18N
        jLabel53.setText("Numero de salle reserver");
        jPanel14.add(jLabel53);
        jLabel53.setBounds(240, 260, 150, 16);
        jPanel14.add(jTextField6);
        jTextField6.setBounds(240, 280, 250, 26);

        jLabel54.setFont(new java.awt.Font("Lato", 1, 13)); // NOI18N
        jLabel54.setText("Horraire");
        jPanel14.add(jLabel54);
        jLabel54.setBounds(240, 320, 50, 16);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Matin", "Aprés Midi", "Soirée" }));
        jPanel14.add(jComboBox2);
        jComboBox2.setBounds(240, 340, 270, 27);

        jButton18.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jButton18.setText("Annuler Reservation");
        jButton18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton18MouseClicked(evt);
            }
        });
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });
        jPanel14.add(jButton18);
        jButton18.setBounds(265, 400, 200, 70);

        javax.swing.GroupLayout annulerReservationLayout = new javax.swing.GroupLayout(annulerReservation.getContentPane());
        annulerReservation.getContentPane().setLayout(annulerReservationLayout);
        annulerReservationLayout.setHorizontalGroup(
            annulerReservationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel14, javax.swing.GroupLayout.DEFAULT_SIZE, 781, Short.MAX_VALUE)
        );
        annulerReservationLayout.setVerticalGroup(
            annulerReservationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(annulerReservationLayout.createSequentialGroup()
                .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, 533, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jDialog3.setSize(new java.awt.Dimension(400, 260));

        jPanel13.setBackground(new java.awt.Color(255, 255, 255));
        jPanel13.setLayout(null);

        jLabel43.setFont(new java.awt.Font("Lato", 1, 14)); // NOI18N
        jLabel43.setText("Les frais de réservation des salles");
        jPanel13.add(jLabel43);
        jLabel43.setBounds(90, 100, 210, 17);

        jLabel44.setIcon(new javax.swing.ImageIcon("/Users/najibboubrim/Desktop/JB/icons8-cash-in-hand-96.png")); // NOI18N
        jPanel13.add(jLabel44);
        jLabel44.setBounds(150, 10, 90, 80);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"250", "400", "500"}
            },
            new String [] {
                "Matin", "Aprés Midi", "Soirée"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        jPanel13.add(jScrollPane2);
        jScrollPane2.setBounds(30, 150, 340, 60);

        javax.swing.GroupLayout jDialog3Layout = new javax.swing.GroupLayout(jDialog3.getContentPane());
        jDialog3.getContentPane().setLayout(jDialog3Layout);
        jDialog3Layout.setHorizontalGroup(
            jDialog3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        jDialog3Layout.setVerticalGroup(
            jDialog3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jDialog4.setBounds(new java.awt.Rectangle(0, 22, 400, 260));

        jPanel16.setBackground(new java.awt.Color(255, 255, 255));
        jPanel16.setLayout(null);

        jLabel61.setFont(new java.awt.Font("Lato", 1, 14)); // NOI18N
        jLabel61.setText("Facture pour votre réservation");
        jPanel16.add(jLabel61);
        jLabel61.setBounds(110, 100, 200, 17);

        jLabel62.setIcon(new javax.swing.ImageIcon("/Users/najibboubrim/Desktop/JB/icons8-bill-96.png")); // NOI18N
        jPanel16.add(jLabel62);
        jLabel62.setBounds(150, 10, 90, 80);

        facture_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nom", "Prenom", "Somme"
            }
        ));
        jScrollPane3.setViewportView(facture_table);

        jPanel16.add(jScrollPane3);
        jScrollPane3.setBounds(10, 130, 380, 120);

        javax.swing.GroupLayout jDialog4Layout = new javax.swing.GroupLayout(jDialog4.getContentPane());
        jDialog4.getContentPane().setLayout(jDialog4Layout);
        jDialog4Layout.setHorizontalGroup(
            jDialog4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel16, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        jDialog4Layout.setVerticalGroup(
            jDialog4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel16, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        enregistrerVFrame.setBounds(new java.awt.Rectangle(0, 22, 781, 533));

        jPanel18.setBackground(new java.awt.Color(255, 255, 255));
        jPanel18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel18MouseClicked(evt);
            }
        });
        jPanel18.setLayout(null);

        jLabel69.setFont(new java.awt.Font("Seravek", 1, 24)); // NOI18N
        jLabel69.setForeground(new java.awt.Color(255, 255, 255));
        jLabel69.setText("Enregistrer Versement");
        jPanel18.add(jLabel69);
        jLabel69.setBounds(280, 20, 240, 30);

        jLabel70.setIcon(new javax.swing.ImageIcon("/Users/najibboubrim/Desktop/JB/BG.jpg")); // NOI18N
        jPanel18.add(jLabel70);
        jLabel70.setBounds(0, 0, 800, 60);

        jLabel71.setFont(new java.awt.Font("Lato", 1, 16)); // NOI18N
        jLabel71.setText("Veuillez remplir les informations suivants :");
        jPanel18.add(jLabel71);
        jLabel71.setBounds(240, 150, 320, 20);

        jLabel72.setFont(new java.awt.Font("Lato", 1, 13)); // NOI18N
        jLabel72.setText("Numero d'usager");
        jPanel18.add(jLabel72);
        jLabel72.setBounds(240, 200, 120, 16);
        jPanel18.add(jTextField11);
        jTextField11.setBounds(240, 220, 250, 26);

        jButton21.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jButton21.setText("Enregister");
        jButton21.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton21MouseClicked(evt);
            }
        });
        jButton21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton21ActionPerformed(evt);
            }
        });
        jPanel18.add(jButton21);
        jButton21.setBounds(270, 270, 200, 70);

        javax.swing.GroupLayout enregistrerVFrameLayout = new javax.swing.GroupLayout(enregistrerVFrame.getContentPane());
        enregistrerVFrame.getContentPane().setLayout(enregistrerVFrameLayout);
        enregistrerVFrameLayout.setHorizontalGroup(
            enregistrerVFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel18, javax.swing.GroupLayout.DEFAULT_SIZE, 781, Short.MAX_VALUE)
        );
        enregistrerVFrameLayout.setVerticalGroup(
            enregistrerVFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(enregistrerVFrameLayout.createSequentialGroup()
                .addComponent(jPanel18, javax.swing.GroupLayout.PREFERRED_SIZE, 533, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        verserFrame.setBounds(new java.awt.Rectangle(0, 22, 781, 533));

        jPanel17.setBackground(new java.awt.Color(255, 255, 255));
        jPanel17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel17MouseClicked(evt);
            }
        });
        jPanel17.setLayout(null);

        jLabel63.setFont(new java.awt.Font("Seravek", 1, 24)); // NOI18N
        jLabel63.setForeground(new java.awt.Color(255, 255, 255));
        jLabel63.setText("Verser les frais");
        jPanel17.add(jLabel63);
        jLabel63.setBounds(320, 20, 160, 30);

        jLabel64.setIcon(new javax.swing.ImageIcon("/Users/najibboubrim/Desktop/JB/BG.jpg")); // NOI18N
        jPanel17.add(jLabel64);
        jLabel64.setBounds(0, 0, 800, 60);

        jLabel65.setFont(new java.awt.Font("Lato", 1, 16)); // NOI18N
        jLabel65.setText("Veuillez remplir les informations suivants :");
        jPanel17.add(jLabel65);
        jLabel65.setBounds(240, 150, 320, 20);

        jLabel66.setFont(new java.awt.Font("Lato", 1, 13)); // NOI18N
        jLabel66.setText("Numero d'usager");
        jPanel17.add(jLabel66);
        jLabel66.setBounds(240, 200, 120, 16);
        jPanel17.add(jTextField9);
        jTextField9.setBounds(240, 220, 250, 26);

        jLabel67.setFont(new java.awt.Font("Lato", 1, 13)); // NOI18N
        jLabel67.setText("Somme ( DA )");
        jPanel17.add(jLabel67);
        jLabel67.setBounds(240, 260, 150, 16);

        jButton20.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jButton20.setText("Verser");
        jButton20.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton20MouseClicked(evt);
            }
        });
        jButton20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton20ActionPerformed(evt);
            }
        });
        jPanel17.add(jButton20);
        jButton20.setBounds(265, 400, 200, 70);

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "250", "400", "500" }));
        jPanel17.add(jComboBox4);
        jComboBox4.setBounds(240, 280, 260, 27);

        javax.swing.GroupLayout verserFrameLayout = new javax.swing.GroupLayout(verserFrame.getContentPane());
        verserFrame.getContentPane().setLayout(verserFrameLayout);
        verserFrameLayout.setHorizontalGroup(
            verserFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel17, javax.swing.GroupLayout.DEFAULT_SIZE, 781, Short.MAX_VALUE)
        );
        verserFrameLayout.setVerticalGroup(
            verserFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(verserFrameLayout.createSequentialGroup()
                .addComponent(jPanel17, javax.swing.GroupLayout.PREFERRED_SIZE, 533, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(450, 200, 0, 0));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel1MouseClicked(evt);
            }
        });
        jPanel1.setLayout(null);

        jLabel8.setFont(new java.awt.Font("Seravek", 1, 36)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Gestion de locaux minucipaux");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(100, 40, 500, 70);

        jLabel1.setIcon(new javax.swing.ImageIcon("/Users/najibboubrim/Desktop/JB/BG.jpg")); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 690, 140);

        jLabel2.setIcon(new javax.swing.ImageIcon("/Users/najibboubrim/Desktop/JB/icons8-department-96.png")); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(210, 210, 90, 80);

        jLabel3.setIcon(new javax.swing.ImageIcon("/Users/najibboubrim/Desktop/JB/icons8-apartment-96.png")); // NOI18N
        jPanel1.add(jLabel3);
        jLabel3.setBounds(370, 210, 100, 80);

        jLabel4.setIcon(new javax.swing.ImageIcon("/Users/najibboubrim/Desktop/JB/icons8-home-96.png")); // NOI18N
        jPanel1.add(jLabel4);
        jLabel4.setBounds(290, 220, 90, 70);

        jLabel6.setIcon(new javax.swing.ImageIcon("/Users/najibboubrim/Desktop/JB/icons8-address-96.png")); // NOI18N
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel6);
        jLabel6.setBounds(580, 480, 25, 25);

        jLabel5.setIcon(new javax.swing.ImageIcon("/Users/najibboubrim/Desktop/JB/icons8-ringer-volume-96.png")); // NOI18N
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel5);
        jLabel5.setBounds(610, 480, 30, 25);

        jLabel7.setIcon(new javax.swing.ImageIcon("/Users/najibboubrim/Desktop/JB/icons8-email-sign-96.png")); // NOI18N
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel7);
        jLabel7.setBounds(640, 480, 25, 25);

        jButton1.setFont(new java.awt.Font("Lato", 1, 15)); // NOI18N
        jButton1.setText("S'authentifier");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(260, 310, 180, 50);

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setFont(new java.awt.Font("Lato", 0, 13)); // NOI18N
        jRadioButton1.setText("Gestionnaire Municipal");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jRadioButton1);
        jRadioButton1.setBounds(260, 380, 190, 23);

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setFont(new java.awt.Font("Lato", 0, 13)); // NOI18N
        jRadioButton2.setText("Usager");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jRadioButton2);
        jRadioButton2.setBounds(260, 410, 73, 23);
        jPanel1.add(jSeparator1);
        jSeparator1.setBounds(250, 360, 200, 12);

        jLabel15.setIcon(new javax.swing.ImageIcon("/Users/najibboubrim/Desktop/JB/icons8-admin-settings-male-96.png")); // NOI18N
        jPanel1.add(jLabel15);
        jLabel15.setBounds(230, 370, 50, 40);

        jLabel16.setIcon(new javax.swing.ImageIcon("/Users/najibboubrim/Desktop/JB/icons8-user-96.png")); // NOI18N
        jPanel1.add(jLabel16);
        jLabel16.setBounds(230, 400, 40, 40);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 682, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 517, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        MaterialUIMovement.add(jButton1, MaterialColors.DEEP_PURPLE_50);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        // TODO add your handling code here:
        jFrame1.setVisible(true);
    }//GEN-LAST:event_jLabel6MouseClicked

    private void jPanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseClicked
        // TODO add your handling code here:
        jFrame1.setVisible(false);
        jFrame2.setVisible(false);
        jFrame3.setVisible(false);
    }//GEN-LAST:event_jPanel1MouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        // TODO add your handling code here:
        jFrame2.setVisible(true);
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        // TODO add your handling code here:
        jFrame3.setVisible(true);
    }//GEN-LAST:event_jLabel7MouseClicked

    private void jPanel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel5MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel5MouseClicked

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jPasswordField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        MaterialUIMovement.add(jButton2, MaterialColors.DEEP_PURPLE_50);
        //Connection
            
            String username = jTextField1.getText();
            String password = jPasswordField1.getText();

        try
        {
            int log = 1;
            con = MySqlConnect.ConnectDB();
            st = (Statement)con.createStatement();
            rs = st.executeQuery("select * from Compte");
            
            while(rs.next()) 
            {
                if(rs.getString(3).equals(username) && rs.getString(4).equals(password)) 
                {
                    log = 0;
                    break;
                }
            }
                if(log == 0) {
                    jFrame6.setVisible(true);
                } else {
                    JOptionPane.showMessageDialog(null, "username ou mot de passe incorrect, veuillez les corriger.", "Connnectoin failed", JOptionPane.ERROR_MESSAGE);
                    jTextField1.setText("");
                    jPasswordField1.setText("");
                    jTextField1.grabFocus();
                }

        } catch(SQLException ex){
            Logger lgr = Logger.getLogger(login.class.getName());
            lgr.log(Level.SEVERE, ex.getMessage(), ex);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        MaterialUIMovement.add(jButton3, MaterialColors.DEEP_PURPLE_50);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        // TODO add your handling code here:
        jFrame4.setVisible(false);
    }//GEN-LAST:event_jButton3MouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        if(jRadioButton1.isSelected()) {
            jFrame4.setVisible(true);
        } else if (jRadioButton2.isSelected()) {
            jFrame5.setVisible(true);
        }
        
    }//GEN-LAST:event_jButton1MouseClicked

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jPasswordField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        MaterialUIMovement.add(jButton4, MaterialColors.DEEP_PURPLE_50);
                //Connection
            
            String username = jTextField2.getText();
            String password = jPasswordField2.getText();

        try
        {
            int log = 1;
            con = MySqlConnect.ConnectDB();
            st = (Statement)con.createStatement();
            rs = st.executeQuery("select * from Compte");
            
            while(rs.next()) 
            {
                if(rs.getString(3).equals(username) && rs.getString(4).equals(password)) 
                {
                    log = 0;
                    break;
                }
            }
                if(log == 0) {
                    jFrame7.setVisible(true);
                } else {
                    JOptionPane.showMessageDialog(null, "username ou mot de passe incorrect, veuillez les corriger.", "Connnectoin failed", JOptionPane.ERROR_MESSAGE);
                    jTextField2.setText("");
                    jPasswordField2.setText("");
                    jTextField2.grabFocus();
                }

        } catch(SQLException ex){
            Logger lgr = Logger.getLogger(login.class.getName());
            lgr.log(Level.SEVERE, ex.getMessage(), ex);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseClicked
        // TODO add your handling code here:
        jFrame5.setVisible(false);
    }//GEN-LAST:event_jButton5MouseClicked

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        MaterialUIMovement.add(jButton5, MaterialColors.DEEP_PURPLE_50);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jPanel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel6MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel6MouseClicked

    private void jPanel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel7MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel7MouseClicked

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
        //jFrame6.setVisible(true);
    }//GEN-LAST:event_jButton2MouseClicked

    private void jLabel25MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel25MouseClicked
        // TODO add your handling code here:
        jDialog1.setVisible(true);
    }//GEN-LAST:event_jLabel25MouseClicked

    private void jButton7MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton7MouseEntered
        // TODO add your handling code here:
        jButton7.setBackground(Color.LIGHT_GRAY);
    }//GEN-LAST:event_jButton7MouseEntered

    private void jButton7MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton7MouseExited
        // TODO add your handling code here:
        jButton7.setBackground(Color.WHITE);
    }//GEN-LAST:event_jButton7MouseExited

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton9MouseClicked
        // TODO add your handling code here:
        jFrame6.setVisible(false);
        jDialog1.setVisible(false);
    }//GEN-LAST:event_jButton9MouseClicked

    private void jButton10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton10MouseClicked
        // TODO add your handling code here:
        jDialog1.setVisible(false);
    }//GEN-LAST:event_jButton10MouseClicked

    private void jButton11MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton11MouseExited
        // TODO add your handling code here:
        jButton11.setBackground(Color.WHITE);
    }//GEN-LAST:event_jButton11MouseExited

    private void jButton11MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton11MouseEntered
        // TODO add your handling code here:
        jButton11.setBackground(Color.LIGHT_GRAY);
    }//GEN-LAST:event_jButton11MouseEntered

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton12MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton12MouseExited
        // TODO add your handling code here:
        jButton12.setBackground(Color.WHITE);
    }//GEN-LAST:event_jButton12MouseExited

    private void jButton12MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton12MouseEntered
        // TODO add your handling code here:
        jButton12.setBackground(Color.LIGHT_GRAY);
    }//GEN-LAST:event_jButton12MouseEntered

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton14MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton14MouseExited
        // TODO add your handling code here:
        jButton14.setBackground(Color.WHITE);
    }//GEN-LAST:event_jButton14MouseExited

    private void jButton14MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton14MouseEntered
        // TODO add your handling code here:
        jButton14.setBackground(Color.LIGHT_GRAY);
    }//GEN-LAST:event_jButton14MouseEntered

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton15MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton15MouseExited
        // TODO add your handling code here:
        jButton15.setBackground(Color.WHITE);
    }//GEN-LAST:event_jButton15MouseExited

    private void jButton15MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton15MouseEntered
        // TODO add your handling code here:
        jButton15.setBackground(Color.LIGHT_GRAY);
    }//GEN-LAST:event_jButton15MouseEntered

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jLabel32MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel32MouseClicked
        // TODO add your handling code here:
        jDialog2.setVisible(true);
    }//GEN-LAST:event_jLabel32MouseClicked

    private void jButton13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton13MouseClicked
        // TODO add your handling code here:
        jDialog2.setVisible(false);
        jFrame7.setVisible(false);
    }//GEN-LAST:event_jButton13MouseClicked

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton16MouseClicked
        // TODO add your handling code here:
        jDialog2.setVisible(false);
    }//GEN-LAST:event_jButton16MouseClicked

    private void jButton8MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton8MouseEntered
        // TODO add your handling code here:
        jButton8.setBackground(Color.LIGHT_GRAY);
    }//GEN-LAST:event_jButton8MouseEntered

    private void jButton8MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton8MouseExited
        // TODO add your handling code here:
        jButton8.setBackground(Color.WHITE);
    }//GEN-LAST:event_jButton8MouseExited

    private void jButton6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton6MouseEntered
        // TODO add your handling code here:
        jButton6.setBackground(Color.LIGHT_GRAY);
    }//GEN-LAST:event_jButton6MouseEntered

    private void jButton6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton6MouseExited
        // TODO add your handling code here:
        jButton6.setBackground(Color.WHITE);
    }//GEN-LAST:event_jButton6MouseExited

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        // TODO add your handling code here:
        //jFrame7.setVisible(true);
    }//GEN-LAST:event_jButton4MouseClicked

    private void jPanel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel10MouseClicked
        // TODO add your handling code here:
        jDialog3.setVisible(false);
    }//GEN-LAST:event_jPanel10MouseClicked

    private void jButton7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton7MouseClicked
        // TODO add your handling code here:
        consultFrame.setVisible(true);
    }//GEN-LAST:event_jButton7MouseClicked

    private void jPanel12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel12MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel12MouseClicked

    private void jLabel41MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel41MouseClicked
        // TODO add your handling code here:
        jDialog3.setVisible(true);
    }//GEN-LAST:event_jLabel41MouseClicked

    private void jButton11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton11MouseClicked
        // TODO add your handling code here:
        consultFrame.setVisible(true);
    }//GEN-LAST:event_jButton11MouseClicked

    private void jButton17MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton17MouseClicked
        // TODO add your handling code here:
        Integer numUsager = Integer.parseInt(jTextField3.getText());
        Integer numSallee = Integer.parseInt(jTextField4.getText());
        String horraire = (String) jComboBox1.getSelectedItem();

        try
        {
            con = MySqlConnect.ConnectDB();
            String qr = "select * from Salle WHERE numSalle="+numSallee;
            Statement st3 = con.createStatement();
            ResultSet rs3 = st3.executeQuery(qr);
            
            
            rs3.next();
            if(horraire == "Matin") {
                if(rs3.getInt("reservationMatin") == 1) {
                    JOptionPane.showMessageDialog(null, "Salle déja réserver.", "Erreur", JOptionPane.ERROR_MESSAGE);
                } else {
                    Statement st4 = con.createStatement();
                    int result  = st4.executeUpdate("update Salle SET reservationMatin = 1 WHERE numSalle="+numSallee);
                    JOptionPane.showMessageDialog(null, "Salle réserver avec succès.", "Succès", JOptionPane.INFORMATION_MESSAGE);
                }
            } else { 
                if(horraire == "Aprés Midi") {
                    if(rs3.getInt("reservationApresMidi") == 1) {
                        JOptionPane.showMessageDialog(null, "Salle déja réserver.", "Erreur", JOptionPane.ERROR_MESSAGE);
                    } else {
                        Statement st4 = con.createStatement();
                        int result  = st4.executeUpdate("update Salle SET reservationApresMidi = 1 WHERE numSalle="+numSallee);
                        JOptionPane.showMessageDialog(null, "Salle réserver avec succès.", "Succès", JOptionPane.INFORMATION_MESSAGE);
                    }
                } else {
                    if(horraire == "Soirée") {
                        if(rs3.getInt("reservationSoiree") == 1) {
                            JOptionPane.showMessageDialog(null, "Salle déja réserver.", "Erreur", JOptionPane.ERROR_MESSAGE);
                        } else {
                            Statement st4 = con.createStatement();
                            int result  = st4.executeUpdate("update Salle SET reservationSoiree = 1 WHERE numSalle="+numSallee);
                            JOptionPane.showMessageDialog(null, "Salle réserver avec succès.", "Succès", JOptionPane.INFORMATION_MESSAGE);
                        }   
                    }
                }
            }
            
            
        } catch(SQLException ex){
            Logger lgr = Logger.getLogger(login.class.getName());
            lgr.log(Level.SEVERE, ex.getMessage(), ex);
        }
        
    }//GEN-LAST:event_jButton17MouseClicked

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
        // TODO add your handling code here:
        MaterialUIMovement.add(jButton17, MaterialColors.DEEP_PURPLE_50);
    }//GEN-LAST:event_jButton17ActionPerformed

    private void jButton12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton12MouseClicked
        // TODO add your handling code here:
        reserverSalle.setVisible(true);
    }//GEN-LAST:event_jButton12MouseClicked

    private void jButton18MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton18MouseClicked
        // TODO add your handling code here:
        Integer numUsager = Integer.parseInt(jTextField5.getText());
        Integer numSallee = Integer.parseInt(jTextField6.getText());
        String horraire = (String) jComboBox2.getSelectedItem();

        try
        {
            con = MySqlConnect.ConnectDB();
            String qr = "select * from Salle WHERE numSalle="+numSallee;
            Statement st3 = con.createStatement();
            ResultSet rs3 = st3.executeQuery(qr);
            
            
            rs3.next();
            if(horraire == "Matin") {
                if(rs3.getInt("reservationMatin") == 0) {
                    JOptionPane.showMessageDialog(null, "Salle n'est pas encore réserver.", "Erreur", JOptionPane.ERROR_MESSAGE);
                } else {
                    Statement st4 = con.createStatement();
                    int result  = st4.executeUpdate("update Salle SET reservationMatin = 0 WHERE numSalle="+numSallee);
                    JOptionPane.showMessageDialog(null, "Réservation est bien annulée.", "Succès", JOptionPane.INFORMATION_MESSAGE);
                }
            } else { 
                if(horraire == "Aprés Midi") {
                    if(rs3.getInt("reservationApresMidi") == 0) {
                        JOptionPane.showMessageDialog(null, "Salle n'est pas encore réserver.", "Erreur", JOptionPane.ERROR_MESSAGE);
                    } else {
                        Statement st4 = con.createStatement();
                        int result  = st4.executeUpdate("update Salle SET reservationApresMidi = 0 WHERE numSalle="+numSallee);
                        JOptionPane.showMessageDialog(null, "Réservation est bien annulée.", "Succès", JOptionPane.INFORMATION_MESSAGE);
                    }
                } else {
                    if(horraire == "Soirée") {
                        if(rs3.getInt("reservationSoiree") == 0) {
                            JOptionPane.showMessageDialog(null, "Salle n'est pas encore réserver.", "Erreur", JOptionPane.ERROR_MESSAGE);
                        } else {
                            Statement st4 = con.createStatement();
                            int result  = st4.executeUpdate("update Salle SET reservationSoiree = 0 WHERE numSalle="+numSallee);
                            JOptionPane.showMessageDialog(null, "Réservation est bien annulée.", "Succès", JOptionPane.INFORMATION_MESSAGE);
                        }   
                    }
                }
            }
            
            
        } catch(SQLException ex){
            Logger lgr = Logger.getLogger(login.class.getName());
            lgr.log(Level.SEVERE, ex.getMessage(), ex);
        }
    }//GEN-LAST:event_jButton18MouseClicked

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed
        // TODO add your handling code here:
        MaterialUIMovement.add(jButton17, MaterialColors.DEEP_PURPLE_50);
    }//GEN-LAST:event_jButton18ActionPerformed

    private void jPanel14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel14MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel14MouseClicked

    private void jButton14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton14MouseClicked
        // TODO add your handling code here:
        annulerReservation.setVisible(true);
    }//GEN-LAST:event_jButton14MouseClicked

    private void jButton19MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton19MouseClicked
        // TODO add your handling code here:
        
        int imprNumCompte = Integer.parseInt(jTextField7.getText());
        int imprNumSalle = Integer.parseInt(jTextField8.getText());
        String imprHorraire = (String) jComboBox3.getSelectedItem();
        
        int somme;
        if(imprHorraire == "Matin") {
            somme = 250;
        } else {
            if(imprHorraire == "Aprés Midi") {
                somme = 400;
            } else {
                somme = 500;
            }
        }
        
        try{
        con = MySqlConnect.ConnectDB();
        String query2 = "select * from Usager WHERE numCmpt="+imprNumCompte;
        Statement stf = con.createStatement();
        ResultSet rsf = stf.executeQuery(query2);
        
            rsf.next();
            
        DefaultTableModel model = (DefaultTableModel)facture_table.getModel();
        Object[] row = new Object[6];
        
            row[0] = rsf.getString("nom");
            row[1] = rsf.getString("prenom");
            row[2] = somme;
            model.addRow(row);
            
    } catch(Exception ex) {
        JOptionPane.showMessageDialog(null, ex);
    }
        
        jDialog4.setVisible(true);
    }//GEN-LAST:event_jButton19MouseClicked

    private void jButton19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton19ActionPerformed
        // TODO add your handling code here:
        MaterialUIMovement.add(jButton17, MaterialColors.DEEP_PURPLE_50);
    }//GEN-LAST:event_jButton19ActionPerformed

    private void jPanel15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel15MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel15MouseClicked

    private void jButton6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton6MouseClicked
        // TODO add your handling code here:
        imprimerFrame.setVisible(true);
    }//GEN-LAST:event_jButton6MouseClicked

    private void jButton20MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton20MouseClicked
        // TODO add your handling code here:
        Integer numUsager = Integer.parseInt(jTextField9.getText());
        Integer somme = Integer.parseInt((String) jComboBox4.getSelectedItem());
        
        try{
        con = MySqlConnect.ConnectDB();
        String query = "INSERT INTO Versement(somme, etatEnregistrement, userID) VALUES ("+somme+","+0+" ,"+numUsager+")";
        Statement stV = con.createStatement();
        int rsV = stV.executeUpdate(query);
        JOptionPane.showMessageDialog(null, "Les frais sont bien versés.", "Succès", JOptionPane.INFORMATION_MESSAGE);
        
        
            
        } catch(Exception ex) {
        JOptionPane.showMessageDialog(null, ex);
    }
    }//GEN-LAST:event_jButton20MouseClicked

    private void jButton20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton20ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton20ActionPerformed

    private void jPanel17MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel17MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel17MouseClicked

    private void jButton21MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton21MouseClicked
        // TODO add your handling code here:
        Integer numUsager = Integer.parseInt(jTextField11.getText());
        
        try{
        con = MySqlConnect.ConnectDB();
        String query = "update Versement SET etatEnregistrement = 1 WHERE userID="+numUsager;
        Statement stV = con.createStatement();
        
        int rsV = stV.executeUpdate(query);
        if(rsV > 0){
        JOptionPane.showMessageDialog(null, "Versement enregistré avec succès.", "Succès", JOptionPane.INFORMATION_MESSAGE);
        }else{
        JOptionPane.showMessageDialog(null, "Il n'existe pas de versement.", "Erreur", JOptionPane.ERROR_MESSAGE);
                }
        } catch(Exception ex) {
        //
        //JOptionPane.showMessageDialog(null, ex);
    }
        
    }//GEN-LAST:event_jButton21MouseClicked

    private void jButton21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton21ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton21ActionPerformed

    private void jPanel18MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel18MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel18MouseClicked

    private void jButton15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton15MouseClicked
        // TODO add your handling code here:
        verserFrame.setVisible(true);
    }//GEN-LAST:event_jButton15MouseClicked

    private void jButton8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton8MouseClicked
        // TODO add your handling code here:
        enregistrerVFrame.setVisible(true);
    }//GEN-LAST:event_jButton8MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        try {
		UIManager.setLookAndFeel (new MaterialLookAndFeel ());
            }
	catch (UnsupportedLookAndFeelException e) {
		e.printStackTrace ();
            }
        
        /*sql*/

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFrame annulerReservation;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JFrame consultFrame;
    private javax.swing.JTable consult_table;
    private javax.swing.JFrame enregistrerVFrame;
    private javax.swing.JTable facture_table;
    private javax.swing.JFrame imprimerFrame;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JComboBox jComboBox3;
    private javax.swing.JComboBox jComboBox4;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JDialog jDialog2;
    private javax.swing.JDialog jDialog3;
    private javax.swing.JDialog jDialog4;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JFrame jFrame2;
    private javax.swing.JFrame jFrame3;
    private javax.swing.JFrame jFrame4;
    private javax.swing.JFrame jFrame5;
    private javax.swing.JFrame jFrame6;
    private javax.swing.JFrame jFrame7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel69;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel70;
    private javax.swing.JLabel jLabel71;
    private javax.swing.JLabel jLabel72;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JFrame reserverSalle;
    private javax.swing.JFrame verserFrame;
    // End of variables declaration//GEN-END:variables
}
